// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nffmcnzkkcidihsjeoyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZm1jbnpra2NpZGloc2plb3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTcwODUsImV4cCI6MjA1ODE5MzA4NX0.8pr_Jj4Yxce2z_sdEaD5uUB7J5URED-Y9tvMAXiIocc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);